name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: GouravJena98
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Push Snake Animation to Repository
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist"
          message: "üêç Update contribution snake"
